name: Poll official repo to get the latest release version
on:
  schedule:
    - cron: '16 * * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch branch name of latest version
        run: |
          curl -sL https://api.github.com/repos/Requarks/wiki/releases | \
            jq -r ".[].tag_name" | grep -v rc | sort -r -V | head -n 1 > /tmp/wikijs-latest-branch-name
          echo "REMOTE_BRANCH_NAME=$(cat /tmp/wikijs-latest-branch-name)" >> $GITHUB_ENV
          curl -sL https://github.com/patrickdung/wikijs-crossbuild/raw/main/release-versions/wikijs-latest.txt -o /tmp/wikijs-local-branch-name
          echo "LOCAL_BRANCH_NAME=$(cat /tmp/wikijs-local-branch-name)" >> $GITHUB_ENV
          if [ $(cat /tmp/wikijs-latest-branch-name) == "null" ] || [ $(cat /tmp/wikijs-latest-branch-name) == null ] || [ $(cat /tmp/wikijs-latest-branch-name) == "" ] || [ -z /tmp/wikijs-latest-branch-name ] ; then exit 1 ; else echo "Remote Branch Name is not null"; fi
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$( if [ "${{ env.REMOTE_BRANCH_NAME}}" != "null" ] && [ "${{ env.REMOTE_BRANCH_NAME }}" != "${{ env.LOCAL_BRANCH_NAME }}" ]; then echo "true"; else echo "false"; fi )
      - uses: actions/checkout@v2
        with:
          # https://github.community/t/push-from-action-even-with-pat-does-not-trigger-action/17622/5
          persist-credentials: false
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Patrick Dung'
          git config --global user.email '38665827+patrickdung@users.noreply.github.com'
          #git branch ${{ env.REMOTE_BRANCH_NAME }}
          #git switch ${{ env.REMOTE_BRANCH_NAME }}
          echo ${{ env.REMOTE_BRANCH_NAME }} > release-versions/wikijs-latest.txt
          git commit -am "New release version ${{ env.REMOTE_BRANCH_NAME }}"
          ## By default GH actions push cannot trigger another GH action
          ##git push
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        uses: ad-m/github-push-action@master
        with:
          repository: patrickdung/wikijs-crossbuild
          github_token: ${{ secrets.PUBLISH_TOKEN }}
