name: Release using cross build

on:
  push:
    branches:
      - test
    #paths:
    #  - 'release-versions/*'

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

      - name: Enable Docker experimental mode
        run: |
          echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json

      - name: Checkout repository (to get cross build Dockerfile)
        uses: actions/checkout@v2
        with:
          # repository: patrickdung/wikijs-crossbuild
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry provider
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build and push to container registry
        uses: docker/build-push-action@v2
        # ./Dockerfile is in the upper directory
        # ./wiki is the wikijs source code repo
        with:
          #context: ./wiki
          #file: ./Dockerfile
          ##build-args: |
          ##  ARCH=${{ env.TO_BE_FIXED }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: registry.gitlab.com/patrickdung/wikijs:test
